spring.application.name=user-service
server.port=8081
spring.grpc.server.port=9093

spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=user_service
spring.datasource.password=${SERVICE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Keycloak / OAuth2 resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/home-energy-tracker-security-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/home-energy-tracker-security-realm/protocol/openid-connect/certs

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
