spring.application.name=insight-service
server.port=8086

#datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/insight_service
spring.datasource.username=insight_service
spring.datasource.password=${SERVICE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.protocol=smtp

insight.from-address=insights@home-energy-tracker.local

#kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=insight-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=energyAlertEvent:com.demo.common.kafka.event.EnergyAlertEvent

#influxdb
influxDB.url=http://localhost:8072
influxDB.token=${INFLUXDB_INIT_ADMIN_TOKEN}
influxDB.org=home-energy-tracker
influxDB.bucket=usage-bucket

#grpc
spring.grpc.client.channels.device-service.address=static://localhost:9092
spring.grpc.client.channels.device-service.negotiation-type=plaintext

spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.base-url=http://localhost:11434
# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
