spring.application.name=usage-service
server.port=8084

#kafka-consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=energyUsageEvent:com.demo.common.kafka.event.EnergyUsageEvent

#kafka-producer
spring.kafka.producer.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=energyAlertEvent:com.demo.common.kafka.event.EnergyAlertEvent

influxDB.url=http://localhost:8072
influxDB.token=${INFLUXDB_INIT_ADMIN_TOKEN}
influxDB.org=home-energy-tracker
influxDB.bucket=usage-bucket

spring.grpc.client.channels.device-service.address=static://localhost:9092
spring.grpc.client.channels.device-service.negotiation-type=plaintext
spring.grpc.client.channels.user-service.address=static://localhost:9093
spring.grpc.client.channels.user-service.negotiation-type=plaintext
# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
